### ISSUE TITLE
idb2pat.py issue on IDA 7.5

### ISSUE THREAD

**Issue by KulaGGin** [fireeye/flare-ida#104]
If you run idb2pat.py on IDA version 7.5, you'll get this error:
```
 error: Traceback (most recent call last):
  File "<string>", line 478, in <module>
  File "<string>", line 455, in main
  File "<string>", line 416, in get_pat_file
NameError: global name 'askfile_c' is not defined
```

Which is caused by newer version of IDA and renaming of the `askfile_c` member to `ask_file` in the `ida_kernwin` type, as explained in [this porting guide](https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml) by hex-rays.

There are many more errors like this one for many members in different types.

One possible solution I see is to have 2 versions of the file now: idb2pat.py and idb2pat_74plus.py for appropriate IDA version.

**Comment by mr-tz** [comment]
I think `idaapi.ask_file` works in all versions and we can just replace this API call.
Alternatively, we could check the IDA version and pick the appropriate API.
