### ISSUE TITLE
print_tinfo expected 8 arguments, got 7

### ISSUE THREAD

**Issue by hacksysteam** [fireeye/flare-ida#15]
Hi FLARE Team,

```
ApplyCalleeType: Exception caught: print_tinfo expected 8 arguments, got 7
Traceback (most recent call last):
  File "C:\Tools\IDA\python\flare\apply_callee_type.py", line 267, in run
    typename = idaapi.print_tinfo('', '', 0, 0, idaapi.PRTYPE_1LINE, tinfo, '', '')
  File "C:\Tools\IDA\python\idaapi.py", line 36101, in print_tinfo
    return _idaapi.print_tinfo(*args)
TypeError: print_tinfo expected 8 arguments, got 7
```

After looking at idaapi.py

```
def print_tinfo(_args):
  """
    print_tinfo(result, prefix, indent, cmtindent, flags, tif, name,
        cmt) -> bool
    """
  return _idaapi.print_tinfo(_args)
```

Thanks.

**Comment by jhsmith** [comment]
Can you tell us what version of IDA & IDAPython you're running?

**Comment by jhsmith** [comment]
Closing stale ticket due to lack of response.
