### ISSUE TITLE
issue when run python script annotate_IDB_MSDN

### ISSUE THREAD

**Issue by thansau239** [fireeye/flare-ida#17]
i got the issue when run python script annotate_IDB_MSDN, please help me

```
Traceback (most recent call last):
  File "C:/Program Files/IDAPro6.6/python/flare/annotate_IDB_MSDN.py", line 117, in on_ok_button
    IDB_MSDN_Annotator.main(config)
  File "C:/Program Files/IDAPro6.6/python/flare\IDB_MSDN_Annotator\__init__.py", line 523, in main
    functions_map = parse_xml_data_files(msdn_data_dir)
  File "C:/Program Files/IDAPro6.6/python/flare\IDB_MSDN_Annotator\__init__.py", line 486, in parse_xml_data_files
    additional_functions = xml_parser.parse(xml_file)
  File "C:/Program Files/IDAPro6.6/python/flare\IDB_MSDN_Annotator\xml_parser.py", line 283, in parse
    parser.parse(xmlfile)
  File "C:\Program Files\IDAPro6.6\lib\xml\sax\expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Program Files\IDAPro6.6\lib\xml\sax\xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "C:\Program Files\IDAPro6.6\lib\xml\sax\expatreader.py", line 211, in feed
    self._err_handler.fatalError(exc)
  File "C:\Program Files\IDAPro6.6\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: C:\Program Files\IDAPro6.6\python\flare\annotate_IDB_MSDN.py:1:2: not well-formed (invalid token)
```

Thank you very much!

**Comment by mr-tz** [comment]
If this is still relevant, can you please check whether the following file works for you after unzipping it?
https://github.com/mr-tz/flare-ida/blob/master/MSDN_data/msdn_data.zip
Please reopen this issue if you need further assistance.
