### ISSUE TITLE
idb2pat - OverflowError on 64 bit applications.

### ISSUE THREAD

**Issue by Convery** [fireeye/flare-ida#23]
The script works great on x86 applications but fails on x64 applications.

ERROR:idb2pat:make_func_sigs:Python int too large to convert to C long
Traceback (most recent call last):
  File "X:/Software/IDA 6.8/python/flare/idb2pat.py", line 370, in make_func_sigs
    sigs.append(make_func_sig(config, f))
  File "X:/Software/IDA 6.8/python/flare/idb2pat.py", line 219, in make_func_sig
    ref_loc = find_ref_loc(config, ea, ref)
  File "X:/Software/IDA 6.8/python/flare/idb2pat.py", line 142, in find_ref_loc
    for i in xrange(ea, get_item_end(ea) - config.pointer_size + 1):
OverflowError: Python int too large to convert to C long
ERROR:idb2pat:make_func_sigs:Failed to create signature for function at [...]

**Comment by Convery** [comment]
Also fails on 32bit PPC.

ERROR:idb2pat:make_func_sigs:Python int too large to convert to C long
Traceback (most recent call last):
  File "X:/Software/IDA 6.8/python/flare/idb2pat.py", line 370, in make_func_sigs
    sigs.append(make_func_sig(config, f))
  File "X:/Software/IDA 6.8/python/flare/idb2pat.py", line 192, in make_func_sig
    ref_loc = find_ref_loc(config, ea, ref)
  File "X:/Software/IDA 6.8/python/flare/idb2pat.py", line 142, in find_ref_loc
    for i in xrange(ea, get_item_end(ea) - config.pointer_size + 1):
OverflowError: Python int too large to convert to C long
ERROR:idb2pat:make_func_sigs:Failed to create signature for function at [...]
