### ISSUE TITLE
Problems with MSDN_Crawler (MSDN Annotation) - FEB/12/2016

### ISSUE THREAD

**Issue by alexandreborges** [fireeye/flare-ida#25]
A couple of weeks ago I’ve download the flare-ida and, among the scripts, I’ve tested the msdn_crawler. However, I have faced several problems with the parsing process. Additionally, I have tested the MSDN Annotation (MSDN Crawler) in two distinct environments. Few details follow:
1.  The tested environment were WinXP SP2 and Win7x64. 
2.  IDA 6.9 installed (with tilib.exe or tilib64.exe depending of the system)
3.  Python version 2.7.9
4.  The original script from flare-ida package (from https://github.com/fireeye/flare-ida) did not worked for me. Instead of, I downloaded the modified script from http://blog.depressedmarvin.com/upload/2015/02/10/msdn_crawler.py  (Chinese version) and it worked partially (it failed in processing 197 files).
5.   I extracted all help files to Z:\Host_Drive_C\extracted_msdn. Question: Is there some special method (I used 7-zip) to accomplish it? I don' t think so because the Chinese script partialy works with the same extraction.
6.  I installed the  BeautifulSoup package (version 3, because version 4 doesn’t work) by running the following commands: pip install beautifulsoup
7.  I executed the following command:
   C:\flare-ida-master>python -v MSDN_crawler\msdn_crawler.py "Z:\Host_Drive_C\extracted_msdn" "c:\Program Files (x86)\IDA 6.9\tilib64.exe" "C:\Program Files (x86)\IDA 6.9\til\pc"
8.  The output was: 

```
installing zipimport hook
import zipimport  builtin
 installed zipimport hook
 C:\Python27\lib\site.pyc matches C:\Python27\lib\site.py
import site  precompiled from C:\Python27\lib\site.pyc
 C:\Python27\lib\os.pyc matches C:\Python27\lib\os.py
import os  precompiled from C:\Python27\lib\os.pyc
import errno  builtin
import nt  builtin
 C:\Python27\lib\ntpath.pyc matches C:\Python27\lib\ntpath.py
import ntpath  precompiled from C:\Python27\lib\ntpath.pyc
 C:\Python27\lib\stat.pyc matches C:\Python27\lib\stat.py
import stat  precompiled from C:\Python27\lib\stat.pyc
 C:\Python27\lib\genericpath.pyc matches C:\Python27\lib\genericpath.py
import genericpath  precompiled from C:\Python27\lib\genericpath.pyc
 C:\Python27\lib\warnings.pyc matches C:\Python27\lib\warnings.py
import warnings  precompiled from C:\Python27\lib\warnings.pyc
 C:\Python27\lib\linecache.pyc matches C:\Python27\lib\linecache.py
import linecache  precompiled from C:\Python27\lib\linecache.pyc
 C:\Python27\lib\types.pyc matches C:\Python27\lib\types.py
import types  precompiled from C:\Python27\lib\types.pyc
 C:\Python27\lib\UserDict.pyc matches C:\Python27\lib\UserDict.py
import UserDict  precompiled from C:\Python27\lib\UserDict.pyc
 C:\Python27\lib\_abcoll.pyc matches C:\Python27\lib\_abcoll.py
import _abcoll  precompiled from C:\Python27\lib\_abcoll.pyc
 C:\Python27\lib\abc.pyc matches C:\Python27\lib\abc.py
import abc  precompiled from C:\Python27\lib\abc.pyc
 C:\Python27\lib\_weakrefset.pyc matches C:\Python27\lib\_weakrefset.py
import _weakrefset  precompiled from C:\Python27\lib\_weakrefset.pyc
import _weakref  builtin
 C:\Python27\lib\copy_reg.pyc matches C:\Python27\lib\copy_reg.py
import copy_reg  precompiled from C:\Python27\lib\copy_reg.pyc
 C:\Python27\lib\traceback.pyc matches C:\Python27\lib\traceback.py
import traceback  precompiled from C:\Python27\lib\traceback.pyc
 C:\Python27\lib\sysconfig.pyc matches C:\Python27\lib\sysconfig.py
import sysconfig  precompiled from C:\Python27\lib\sysconfig.pyc
 C:\Python27\lib\re.pyc matches C:\Python27\lib\re.py
import re  precompiled from C:\Python27\lib\re.pyc
 C:\Python27\lib\sre_compile.pyc matches C:\Python27\lib\sre_compile.py
import sre_compile  precompiled from C:\Python27\lib\sre_compile.pyc
import _sre  builtin
 C:\Python27\lib\sre_parse.pyc matches C:\Python27\lib\sre_parse.py
import sre_parse  precompiled from C:\Python27\lib\sre_parse.pyc
 C:\Python27\lib\sre_constants.pyc matches C:\Python27\lib\sre_constants.py
import sre_constants  precompiled from C:\Python27\lib\sre_constants.pyc
 C:\Python27\lib\locale.pyc matches C:\Python27\lib\locale.py
import locale  precompiled from C:\Python27\lib\locale.pyc
import encodings  directory C:\Python27\lib\encodings
 C:\Python27\lib\encodings\__init__.pyc matches C:\Python27\lib\encodings\__init__.py
import encodings  precompiled from C:\Python27\lib\encodings\__init__.pyc
 C:\Python27\lib\codecs.pyc matches C:\Python27\lib\codecs.py
import codecs  precompiled from C:\Python27\lib\codecs.pyc
import _codecs  builtin
 C:\Python27\lib\encodings\aliases.pyc matches C:\Python27\lib\encodings\aliases.py
import encodings.aliases  precompiled from C:\Python27\lib\encodings\aliases.pyc
import operator  builtin
 C:\Python27\lib\functools.pyc matches C:\Python27\lib\functools.py
import functools  precompiled from C:\Python27\lib\functools.pyc
import _functools  builtin
import _locale  builtin
 C:\Python27\lib\encodings\cp1252.pyc matches C:\Python27\lib\encodings\cp1252.py
import encodings.cp1252  precompiled from C:\Python27\lib\encodings\cp1252.pyc
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
 C:\Python27\lib\csv.pyc matches C:\Python27\lib\csv.py
import csv  precompiled from C:\Python27\lib\csv.pyc
import _csv  builtin
import cStringIO  builtin
import logging  directory C:\Python27\lib\logging
 C:\Python27\lib\logging\__init__.pyc matches C:\Python27\lib\logging\__init__.py
import logging  precompiled from C:\Python27\lib\logging\__init__.pyc
import time  builtin
 C:\Python27\lib\weakref.pyc matches C:\Python27\lib\weakref.py
import weakref  precompiled from C:\Python27\lib\weakref.pyc
import thread  builtin
 C:\Python27\lib\threading.pyc matches C:\Python27\lib\threading.py
import threading  precompiled from C:\Python27\lib\threading.pyc
 C:\Python27\lib\collections.pyc matches C:\Python27\lib\collections.py
import collections  precompiled from C:\Python27\lib\collections.pyc
import _collections  builtin
 C:\Python27\lib\keyword.pyc matches C:\Python27\lib\keyword.py
import keyword  precompiled from C:\Python27\lib\keyword.pyc
 C:\Python27\lib\heapq.pyc matches C:\Python27\lib\heapq.py
import heapq  precompiled from C:\Python27\lib\heapq.pyc
import itertools  builtin
import _heapq  builtin
 C:\Python27\lib\atexit.pyc matches C:\Python27\lib\atexit.py
import atexit  precompiled from C:\Python27\lib\atexit.pyc
 C:\Python27\lib\pprint.pyc matches C:\Python27\lib\pprint.py
import pprint  precompiled from C:\Python27\lib\pprint.pyc
 C:\Python27\lib\site-packages\BeautifulSoup.pyc matches C:\Python27\lib\site-packages\BeautifulSoup.py
import BeautifulSoup  precompiled from C:\Python27\lib\site-packages\BeautifulSoup.pyc
 C:\Python27\lib\__future__.pyc matches C:\Python27\lib\__future__.py
import __future__  precompiled from C:\Python27\lib\__future__.pyc
 C:\Python27\lib\sgmllib.pyc matches C:\Python27\lib\sgmllib.py
import sgmllib  precompiled from C:\Python27\lib\sgmllib.pyc
 C:\Python27\lib\markupbase.pyc matches C:\Python27\lib\markupbase.py
import markupbase  precompiled from C:\Python27\lib\markupbase.pyc
 C:\Python27\lib\htmlentitydefs.pyc matches C:\Python27\lib\htmlentitydefs.py
import htmlentitydefs  precompiled from C:\Python27\lib\htmlentitydefs.pyc
 C:\flare-ida-master\MSDN_crawler\extract_til_constant_info.pyc matches C:\flare-ida-master\MSDN_crawler\extract_t
il_constant_info.py
import extract_til_constant_info  precompiled from C:\flare-ida-master\MSDN_crawler\extract_til_constant_info.pyc
 C:\Python27\lib\subprocess.pyc matches C:\Python27\lib\subprocess.py
import subprocess  precompiled from C:\Python27\lib\subprocess.pyc
import gc  builtin
import msvcrt  builtin
import _subprocess  builtin
MSDN crawler based on zynamics msdn-crawler - Copyright 2010
 C:\Python27\lib\encodings\ascii.pyc matches C:\Python27\lib\encodings\ascii.py
import encodings.ascii  precompiled from C:\Python27\lib\encodings\ascii.pyc
Traceback (most recent call last):
  File "MSDN_crawler\msdn_crawler.py", line 413, in <module>
    main()
  File "MSDN_crawler\msdn_crawler.py", line 398, in main
    (file_counter, results) = parse_files(msdn_directory, tilib_exe, til_dir)
  File "MSDN_crawler\msdn_crawler.py", line 371, in parse_files
    result = parse_file(os.path.join(root, file), const_enum)
  File "MSDN_crawler\msdn_crawler.py", line 276, in parse_file
    return parse_new_style(file, content, const_enum)
  File "MSDN_crawler\msdn_crawler.py", line 183, in parse_new_style
    parsed_html.find_all(width='60%')]
TypeError: 'NoneType' object is not callable
```
1.  By using the Chinese version, the output was (during the first lines):

```
…..

'ascii' codec can't encode character u'\xa0' in position 174: ordinal not in range(128) - ERROR: virtualallocex.htm
```

And the last three lines were:

```
Parsed 341767 files
Extracted information about 34214 functions
ERROR processing 197 files
```
1.   I renamed the msdn_data_nn.xml file to msdn_data.xml and copied it to IDA 6.8 directory.  After having configured the plugin (executing the annotate_IDB_MSDN.py script) and having tested it with a malware, the following message came up  at IDA Pro output section (probably, because of 197 errors): 

```
MSDN Annotator SUMMARY
----------------------------------
Functions not found
-------------------
  1            LCMapStringW
  2            SetHandleCount
  3            LCMapStringA
  4            MultiByteToWideChar
  5            WideCharToMultiByte
  6            InternetOpenUrlA
  7            VirtualAlloc
```

I’ve already seen someone reporting the same problem, but I wasn’t able to find the appropriate explanation.

Please, could you help me?

Thank you.

AB.

**Comment by mr-tz** [comment]
If this is still relevant, can you please check whether the following file works for you after unzipping it?
https://github.com/mr-tz/flare-ida/blob/master/MSDN_data/msdn_data.zip
