### ISSUE TITLE
MSDN_MACROS not defined in apply_callee_type?

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-ida#34]
see https://github.com/fireeye/flare-ida/blob/4fdc6aeaf997576410afdd3f06e6020898e2a09d/python/flare/apply_callee_type.py#L218

**Comment by strictlymike** [comment]
I get the same when I try pasting a function prototype into the `Enter Type Declaration` edit box and click `OK`.

```ApplyCalleeType: Exception caught: global name 'MSDN_MACROS' is not defined
Traceback (most recent call last):
  File "path\to\ida\python\flare\apply_callee_type.py", line 249, in run
    decl = self.convertUserType(str(dlg.getUserText()))
  File "path\to\ida\python\flare\apply_callee_type.py", line 218, in convertUserType
    for sub in MSDN_MACROS:
NameError: global name 'MSDN_MACROS' is not defined
```

**Comment by keithjjones** [comment]
Same here.  👍

**Comment by jhsmith** [comment]
Thanks for the report. Now fixed in master branch. Error from an old code cleanup patch.
