### ISSUE TITLE
annotate_IDB_MSDN.py not working w IDA 6.95

### ISSUE THREAD

**Issue by peta909** [fireeye/flare-ida#49]
I tried running the plugin w the db file from the url https://github.com/mr-tz/flare-ida/blob/master/MSDN_data/msdn_data.zip

the plugin threw this error:
Traceback (most recent call last):
  File "C:/bin/flare/annotate_IDB_MSDN.py", line 118, in on_ok_button
    IDB_MSDN_Annotator.main(config)
  File "C:/bin/flare\IDB_MSDN_Annotator\__init__.py", line 521, in main
    functions_map = parse_xml_data_files(msdn_data_dir)
  File "C:/bin/flare\IDB_MSDN_Annotator\__init__.py", line 484, in parse_xml_data_files
    additional_functions = xml_parser.parse(xml_file)
  File "C:/bin/flare\IDB_MSDN_Annotator\xml_parser.py", line 283, in parse
    parser.parse(xmlfile)
  File "C:\bin\Python27\Lib\xml\sax\expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\bin\Python27\Lib\xml\sax\xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "C:\bin\Python27\Lib\xml\sax\expatreader.py", line 217, in feed
    self._err_handler.fatalError(exc)
  File "C:\bin\Python27\Lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: C:/bin/flare\annotate_IDB_MSDN.py:1:2: not well-formed (invalid token)

**Comment by mr-tz** [comment]
Please make sure that the `MSDN Data Directory` only contains valid XML files. The plugin tries to parse every file and fails on non-XML data, e.g. ZIP files. Does this resolve your issue?

**Comment by peta909** [comment]
Yes it resolve my issue.

Thank you so much mr-tz.

**Comment by mr-tz** [comment]
Cool, you are welcome!
