### ISSUE TITLE
issue when execute MSDN Crawler

### ISSUE THREAD

**Issue by lingchuanlee** [fireeye/flare-ida#5]
i got the issue of MSDN Crawler, anyone has this issue when execute MSDN Crawler?

```
C:\Program Files\IDA 6.4>python msdn_crawler.py "C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\Help\\1033" "C:\\Program Files\\IDA 6.4\\tilib.exe" "C:\\Program Files\\IDA 6.4\\til\\pc"
MSDN crawler based on zynamics msdn-crawler - Copyright 2010
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\bc31.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\bc31.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\bc5dos.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\bc5dos.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\bc5w16.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\bc5w16.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\bcb4win.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\bcb4win.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\bcb5win.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\bcb5win.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\geos.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\geos.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\gnuwin.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\gnuwin.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\ms16dos.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\ms16dos.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\ms16win.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\ms16win.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\mscor.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\mscor.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\mssdk.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\mssdk.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\mssdk_2000.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\mssdk_2000.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\mssdk_nt.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\mssdk_nt.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\mssdk_vista.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\mssdk_vista.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\mssdk_win7.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\mssdk_win7.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\mssdk_ws03.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\mssdk_ws03.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\nlm.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\nlm.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\ntapi.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\ntapi.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\ntddk.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\ntddk.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\ntddk64.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\ntddk64.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\vc10.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\vc10.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\vc10_64.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\vc10_64.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\vc6win.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\vc6win.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\vc8amd64.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\vc8amd64.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\vc9.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\vc9.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\w16dos.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\w16dos.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\w16os2.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\w16os2.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\w32dos.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\w32dos.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\w32os2.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\w32os2.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\wdm.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\wdm.til']' returned non-zero exit status 1
WARNING:til_extractor:Error calling tilib.exe with C:\Program Files\IDA 6.4\til\pc\wnet.til -- Command '['C:\\Program Files\\IDA 6.4\\tilib.exe', '-l', 'C:\\Program Files\\IDA 6.4\\til\\pc\\wnet.til']' returned non-zero exit status 1
Traceback (most recent call last):
  File "msdn_crawler.py", line 413, in <module>
    main()
  File "msdn_crawler.py", line 398, in main
    (file_counter, results) = parse_files(msdn_directory, tilib_exe, til_dir)
  File "msdn_crawler.py", line 357, in parse_files
    const_enum = extract_til_constant_info.main(tilib_exe, til_dir)
  File "C:\Program Files\IDA 6.4\extract_til_constant_info.py", line 95, in main
    for enum_name, enum in enums.iteritems():
UnboundLocalError: local variable 'enums' referenced before assignment
```

C:\Program Files\IDA 6.4>

**Comment by mr-tz** [comment]
Closing this old issue with missing response. Please reopen if it's still relevant.
