### ISSUE TITLE
stackstrings-plugin excepion

### ISSUE THREAD

**Issue by zhanglGitHub** [fireeye/flare-ida#77]
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/stackstrings_plugin.py", line 67, in run
    flare.stackstrings.main()
  File "C:\Python27\Lib\flare\stackstrings.py", line 276, in main
    vw = jayutils.loadWorkspace(filePath)
  File "C:\Python27\Lib\flare\jayutils.py", line 341, in loadWorkspace
    vw.loadFromFile(filename)
  File "C:\Python27\Lib\vivisect\__init__.py", line 2265, in loadFromFile
    fname = mod.parseFile(self, filename, baseaddr=baseaddr)
  File "C:\Python27\Lib\vivisect\parsers\blob.py", line 45, in parseFile
    raise Exception('Blob loader *requires* arch option (-O viv.parsers.blob.arch="<archname>")')
Exception: Blob loader *requires* arch option (-O viv.parsers.blob.arch="<archname>

**Comment by maoguai** [comment]
I have meet the same problem? how did you solve it?
